[basic]
data_dir = "./data"
log_dir = "./logs"
model_dir = "./models"

[server]
port = 3000
db_url = "192.168.1.222:5432"
db_user = "sakuya"
db_password = "^ghf%GHD*2024"
db_name = "postgres"

[training]
global_device_type = "cuda"
attn_implementation = "sdpa"

[credential]
username = "admin"
password = "admin"
