[basic]
data_dir = "./data"
log_dir = "./logs"
model_dir = "./models"

[server]
port = 3000
db_url = "localhost:5432"
db_user = "postgres"
db_password = "123456"
db_name = "postgres"
token_public_key = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA86QiBBSg108AbQ4CSkBT
2ErTOUzYq9/8hSxpx+RZcSIfakKMx3vzF8/6F4ogq41hFNDxjvUx0KjRhlthWuNn
x7B7iQqgUccLZniS3SZdj+qfVF6BKOfHGUsu6u5J1QW1Si4/rCIg84dqI1Cop7VK
rfUWcwof0BhBNcIKX1CbgtbZTrKR+hkrCqwA7NaCwU/YbMviknSOeCbKLMKTCQpE
4OeO7qlu2aEYfMMay9+PjraYtaLMPF07mNwj+95ztMx51BfCaPwJ9+eYygtHUXWm
BmioT/jqQz5wXURe3lRuytamOklx8Iq7meL2o8VP6f/UU4Af9X11fEf+xDzBnIjW
awIDAQAB
-----END PUBLIC KEY-----
"""
token_private_key = """
-----BEGIN PRIVATE KEY-----
MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDzpCIEFKDXTwBt
DgJKQFPYStM5TNir3/yFLGnH5FlxIh9qQozHe/MXz/oXiiCrjWEU0PGO9THQqNGG
W2Fa42fHsHuJCqBRxwtmeJLdJl2P6p9UXoEo58cZSy7q7knVBbVKLj+sIiDzh2oj
UKintUqt9RZzCh/QGEE1wgpfUJuC1tlOspH6GSsKrADs1oLBT9hsy+KSdI54Jsos
wpMJCkTg547uqW7ZoRh8wxrL34+Otpi1osw8XTuY3CP73nO0zHnUF8Jo/An355jK
C0dRdaYGaKhP+OpDPnBdRF7eVG7K1qY6SXHwiruZ4vajxU/p/9RTgB/1fXV8R/7E
PMGciNZrAgMBAAECggEBAISPE7bWpmAe6qNrENHnR/cRVvUBG44AEvs+G9uXIRbN
svv0c3YBuVSGYpK2I2pTRLO3rwXR4CWgBEeupjx2J7vdCImaT3nO6yP4jCdovVUV
GVUlCe8AlDHt1vwZY/BT57wRh7EW7Iizb4sBUpHUsGoPRASZSI/G8ovWJCCR0dqQ
DOUjzBR23tKUM5ITrta6hDyYd5AEEGIi77CDzEmIXROMl7YAUCyGVWA/WETVxiM2
/DSvPqscvR84ro4UGJIhE6Q5i3lb1HU55fhupGjMep5I8YOWWbb9CDsTRZ9e6eup
WG6g+7FoMivQLpPlffKIY+wsaROJ31XRNQnrVfjP4kkCgYEA9bbkHu/K5aTUu5Xs
xVMo1GfK1pt5YrA3As+Rw4FR0oE4bE+CahSuHf6m5I3cs4+nb2LuymtGl2lK6uy8
6YZ+nGtjzCokzU4+jpgGERmHQD5nyC4VGQasGo61R7yjk6iHQahBnQzKU4zmSpal
Ozbpyg30dQHAZdSUhkGPDiJzWFcCgYEA/dcGN+ERJIMtHYFrz9XqV4Q6LEpo6DS5
vWNwxj6ishXd4RNcIaWBotzJ2hlaLUS+Izc1pSQYV1nVoYP+l6e73SfSAqUrEPmY
MCavyoIahu5H0y8UZErNoRVUvMerk7Ntgp/DFAfbsQ8lP3XlPu+8eO7DrjnwsKEV
t13AZ41tNg0CgYEAz+VQmgRVbXvLKnQtgr9bumufKXkeeSuTP+OT9xDBxBPlQ276
bvrUXziIyLRm2d5f0lSoqceeUJmb860eIY/ULFCIfcPio3riXw+tgmZRE0A52xty
alxE3auFIg8vb82Vsy3DZjfeMFb0uoM/hhxuLrEj9qPmv8HfcMCjY1gus70CgYEA
rgFBPPrmom3ddlVqj00nWBjHO+dCJLNIA+BvxSXYp1VABPMde98Vj4vkPsKUQ2XV
JRTKjErC+NYXEKIH2vPbXw3V84Q/kmJWheNvK9Wl04rx531lcB6q+NpDfSkun5Am
6J0Vv9xnJ+em8+qgXFVAkHGz5/HF4X57AXid1R5ol90CgYEA1y7RqjPGv+o90Z2R
f1ddBTdvUTywM6MR9t6zj9xc//m8UUJc8+tVp7zHA2pkhASRYWW/yqC4IMItvUqP
7PE1hcIUx+7wqgWuIhqHdTnLR+9TRQgN/aq5gYujrO4jS+YI/KaBt+XYST6FGwJN
N+Cdyek9GJ++KJfVcOtfPQE1ceo=
-----END PRIVATE KEY-----
"""

[training]
global_device_type = "cuda"
attn_implementation = "sdpa"
