[basic]
mode = "local"
data_dir = 'D:\Project\temp\kirine-client\data'
log_dir = 'D:\Project\temp\kirine-client\logs'
model_dir = 'D:\Project\temp\kirine-client\models'

[server]
port = 8000

[training]
hardware_type = "cpu"
attn_implementation = "sdpa"
